language: node_js
before_install:
  - sudo add-apt-repository -y ppa:ondrej/php5
  - sudo apt-get update -qq
  - sudo apt-get install -y php5 php5-cli
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - '0.10'
